[project]
authors = ["Paul"]
entry = "main.sw"
license = "Apache-2.0"
name = "token"

[dependencies]
token = { git = "https://github.com/FuelLabs/sway-libs" }
src_20 = { git = "https://github.com/FuelLabs/sway-standards" }
src_3 = { git = "https://github.com/FuelLabs/sway-standards" }